name: Build & Deploy to Azure WebApp

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - "api/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

env:
  WEBAPP_NAME: cert-admin-webapp-24
  RESOURCE_GROUP: Cloud_Computing_Project
  ACR_NAME: cloudacr24
  IMAGE_NAME: backend

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI - Get ACR login server
        id: acr
        run: |
          ACR_LOGIN=$(az acr show --name $ACR_NAME --query loginServer -o tsv)
          echo "acr_login=$ACR_LOGIN" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t ${{ steps.acr.outputs.acr_login }}/$IMAGE_NAME:$IMAGE_TAG .
          az acr login --name $ACR_NAME
          docker push ${{ steps.acr.outputs.acr_login }}/$IMAGE_NAME:$IMAGE_TAG
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        id: buildpush

      - name: Update Azure Web App container
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name "${{ steps.acr.outputs.acr_login }}/$IMAGE_NAME:${{ steps.buildpush.outputs.image_tag }}" \
            --docker-registry-server-url "https://${{ steps.acr.outputs.acr_login }}"
